<?php

namespace Database\Seeders;

use App\Models\Producto;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        $productos = [
            // Muñecas y Accesorios (categoria_id: 1)
            [
                'categoria_id' => 1,
                'codigo' => 'MUN001',
                'nombre' => 'Barbie Fashionista',
                'descripcion' => 'Muñeca Barbie con ropa moderna y accesorios',
                'precio_compra' => 45.00,
                'precio_venta' => 79.90,
                'stock' => 25,
                'stock_minimo' => 5,
                'estado' => true,
            ],
            [
                'categoria_id' => 1,
                'codigo' => 'MUN002',
                'nombre' => 'Casa de Muñecas 3 Pisos',
                'descripcion' => 'Casa de muñecas con muebles incluidos',
                'precio_compra' => 120.00,
                'precio_venta' => 199.90,
                'stock' => 10,
                'stock_minimo' => 3,
                'estado' => true,
            ],
            [
                'categoria_id' => 1,
                'codigo' => 'MUN003',
                'nombre' => 'Bebé Lloron',
                'descripcion' => 'Muñeca bebé interactiva que llora lágrimas de verdad',
                'precio_compra' => 55.00,
                'precio_venta' => 89.90,
                'stock' => 15,
                'stock_minimo' => 4,
                'estado' => true,
            ],

            // Vehículos y Pistas (categoria_id: 2)
            [
                'categoria_id' => 2,
                'codigo' => 'VEH001',
                'nombre' => 'Hot Wheels Pack 5 Carros',
                'descripcion' => 'Set de 5 carros Hot Wheels metálicos',
                'precio_compra' => 25.00,
                'precio_venta' => 45.90,
                'stock' => 40,
                'stock_minimo' => 10,
                'estado' => true,
            ],
            [
                'categoria_id' => 2,
                'codigo' => 'VEH002',
                'nombre' => 'Pista Hot Wheels Loop',
                'descripcion' => 'Pista con doble loop y lanzador de carros',
                'precio_compra' => 80.00,
                'precio_venta' => 149.90,
                'stock' => 12,
                'stock_minimo' => 3,
                'estado' => true,
            ],
            [
                'categoria_id' => 2,
                'codigo' => 'VEH003',
                'nombre' => 'Camión Monstruo RC',
                'descripcion' => 'Camión a control remoto todo terreno',
                'precio_compra' => 65.00,
                'precio_venta' => 119.90,
                'stock' => 8,
                'stock_minimo' => 2,
                'estado' => true,
            ],

            // Figuras de Acción (categoria_id: 3)
            [
                'categoria_id' => 3,
                'codigo' => 'FIG001',
                'nombre' => 'Spider-Man Figura 30cm',
                'descripcion' => 'Figura articulada de Spider-Man Marvel',
                'precio_compra' => 35.00,
                'precio_venta' => 64.90,
                'stock' => 20,
                'stock_minimo' => 5,
                'estado' => true,
            ],
            [
                'categoria_id' => 3,
                'codigo' => 'FIG002',
                'nombre' => 'Batman con Batimóvil',
                'descripcion' => 'Figura de Batman con vehículo incluido',
                'precio_compra' => 70.00,
                'precio_venta' => 129.90,
                'stock' => 10,
                'stock_minimo' => 3,
                'estado' => true,
            ],
            [
                'categoria_id' => 3,
                'codigo' => 'FIG003',
                'nombre' => 'Transformers Optimus Prime',
                'descripcion' => 'Transformer convertible camión/robot',
                'precio_compra' => 85.00,
                'precio_venta' => 159.90,
                'stock' => 8,
                'stock_minimo' => 2,
                'estado' => true,
            ],

            // Juegos de Mesa (categoria_id: 4)
            [
                'categoria_id' => 4,
                'codigo' => 'JUE001',
                'nombre' => 'Monopoly Clásico',
                'descripcion' => 'Juego de mesa Monopoly edición clásica',
                'precio_compra' => 45.00,
                'precio_venta' => 79.90,
                'stock' => 15,
                'stock_minimo' => 4,
                'estado' => true,
            ],
            [
                'categoria_id' => 4,
                'codigo' => 'JUE002',
                'nombre' => 'UNO Original',
                'descripcion' => 'Juego de cartas UNO para toda la familia',
                'precio_compra' => 12.00,
                'precio_venta' => 24.90,
                'stock' => 50,
                'stock_minimo' => 15,
                'estado' => true,
            ],
            [
                'categoria_id' => 4,
                'codigo' => 'JUE003',
                'nombre' => 'Jenga Clásico',
                'descripcion' => 'Torre de bloques de madera apilables',
                'precio_compra' => 20.00,
                'precio_venta' => 39.90,
                'stock' => 25,
                'stock_minimo' => 6,
                'estado' => true,
            ],

            // Peluches (categoria_id: 5)
            [
                'categoria_id' => 5,
                'codigo' => 'PEL001',
                'nombre' => 'Oso de Peluche Grande',
                'descripcion' => 'Oso de peluche suave 60cm',
                'precio_compra' => 30.00,
                'precio_venta' => 59.90,
                'stock' => 20,
                'stock_minimo' => 5,
                'estado' => true,
            ],
            [
                'categoria_id' => 5,
                'codigo' => 'PEL002',
                'nombre' => 'Pikachu Peluche',
                'descripcion' => 'Peluche oficial de Pokémon Pikachu',
                'precio_compra' => 25.00,
                'precio_venta' => 49.90,
                'stock' => 30,
                'stock_minimo' => 8,
                'estado' => true,
            ],
            [
                'categoria_id' => 5,
                'codigo' => 'PEL003',
                'nombre' => 'Stitch Peluche',
                'descripcion' => 'Peluche de Stitch de Lilo & Stitch',
                'precio_compra' => 28.00,
                'precio_venta' => 54.90,
                'stock' => 25,
                'stock_minimo' => 6,
                'estado' => true,
            ],

            // LEGO y Bloques (categoria_id: 6)
            [
                'categoria_id' => 6,
                'codigo' => 'LEG001',
                'nombre' => 'LEGO City Estación Policía',
                'descripcion' => 'Set LEGO estación de policía 743 piezas',
                'precio_compra' => 150.00,
                'precio_venta' => 279.90,
                'stock' => 8,
                'stock_minimo' => 2,
                'estado' => true,
            ],
            [
                'categoria_id' => 6,
                'codigo' => 'LEG002',
                'nombre' => 'LEGO Star Wars X-Wing',
                'descripcion' => 'Nave X-Wing de Star Wars 567 piezas',
                'precio_compra' => 180.00,
                'precio_venta' => 329.90,
                'stock' => 6,
                'stock_minimo' => 2,
                'estado' => true,
            ],
            [
                'categoria_id' => 6,
                'codigo' => 'LEG003',
                'nombre' => 'Bloques Creativos 500pcs',
                'descripcion' => 'Set de bloques creativos multicolor',
                'precio_compra' => 35.00,
                'precio_venta' => 69.90,
                'stock' => 20,
                'stock_minimo' => 5,
                'estado' => true,
            ],

            // Juguetes Educativos (categoria_id: 7)
            [
                'categoria_id' => 7,
                'codigo' => 'EDU001',
                'nombre' => 'Microscopio Infantil',
                'descripcion' => 'Microscopio educativo para niños con muestras',
                'precio_compra' => 40.00,
                'precio_venta' => 79.90,
                'stock' => 12,
                'stock_minimo' => 3,
                'estado' => true,
            ],
            [
                'categoria_id' => 7,
                'codigo' => 'EDU002',
                'nombre' => 'Kit de Química',
                'descripcion' => 'Set de experimentos químicos seguros',
                'precio_compra' => 55.00,
                'precio_venta' => 99.90,
                'stock' => 10,
                'stock_minimo' => 3,
                'estado' => true,
            ],
            [
                'categoria_id' => 7,
                'codigo' => 'EDU003',
                'nombre' => 'Rompecabezas Mapa Mundial',
                'descripcion' => 'Puzzle educativo 500 piezas del mundo',
                'precio_compra' => 18.00,
                'precio_venta' => 34.90,
                'stock' => 30,
                'stock_minimo' => 8,
                'estado' => true,
            ],

            // Deportes y Aire Libre (categoria_id: 8)
            [
                'categoria_id' => 8,
                'codigo' => 'DEP001',
                'nombre' => 'Pelota de Fútbol N°5',
                'descripcion' => 'Balón de fútbol profesional tamaño oficial',
                'precio_compra' => 25.00,
                'precio_venta' => 49.90,
                'stock' => 35,
                'stock_minimo' => 10,
                'estado' => true,
            ],
            [
                'categoria_id' => 8,
                'codigo' => 'DEP002',
                'nombre' => 'Set de Bolos Infantil',
                'descripcion' => 'Juego de bolos plásticos para niños',
                'precio_compra' => 22.00,
                'precio_venta' => 44.90,
                'stock' => 18,
                'stock_minimo' => 5,
                'estado' => true,
            ],
            [
                'categoria_id' => 8,
                'codigo' => 'DEP003',
                'nombre' => 'Patines en Línea',
                'descripcion' => 'Patines ajustables con protecciones',
                'precio_compra' => 70.00,
                'precio_venta' => 129.90,
                'stock' => 10,
                'stock_minimo' => 3,
                'estado' => true,
            ],

            // Electrónicos (categoria_id: 9)
            [
                'categoria_id' => 9,
                'codigo' => 'ELE001',
                'nombre' => 'Tablet Infantil 7"',
                'descripcion' => 'Tablet educativa con control parental',
                'precio_compra' => 150.00,
                'precio_venta' => 279.90,
                'stock' => 8,
                'stock_minimo' => 2,
                'estado' => true,
            ],
            [
                'categoria_id' => 9,
                'codigo' => 'ELE002',
                'nombre' => 'Robot Programable',
                'descripcion' => 'Robot educativo programable por app',
                'precio_compra' => 120.00,
                'precio_venta' => 219.90,
                'stock' => 6,
                'stock_minimo' => 2,
                'estado' => true,
            ],
            [
                'categoria_id' => 9,
                'codigo' => 'ELE003',
                'nombre' => 'Walkie Talkie Par',
                'descripcion' => 'Set de 2 walkie talkies alcance 3km',
                'precio_compra' => 35.00,
                'precio_venta' => 69.90,
                'stock' => 15,
                'stock_minimo' => 4,
                'estado' => true,
            ],

            // Disfraces y Accesorios (categoria_id: 10)
            [
                'categoria_id' => 10,
                'codigo' => 'DIS001',
                'nombre' => 'Disfraz Princesa Elsa',
                'descripcion' => 'Disfraz completo de Elsa de Frozen',
                'precio_compra' => 45.00,
                'precio_venta' => 89.90,
                'stock' => 12,
                'stock_minimo' => 3,
                'estado' => true,
            ],
            [
                'categoria_id' => 10,
                'codigo' => 'DIS002',
                'nombre' => 'Disfraz Spider-Man',
                'descripcion' => 'Traje completo de Spider-Man con máscara',
                'precio_compra' => 50.00,
                'precio_venta' => 94.90,
                'stock' => 15,
                'stock_minimo' => 4,
                'estado' => true,
            ],
            [
                'categoria_id' => 10,
                'codigo' => 'DIS003',
                'nombre' => 'Set Doctor Infantil',
                'descripcion' => 'Maletín de doctor con accesorios',
                'precio_compra' => 28.00,
                'precio_venta' => 54.90,
                'stock' => 20,
                'stock_minimo' => 5,
                'estado' => true,
            ],
        ];

        foreach ($productos as $producto) {
            Producto::create($producto);
        }
    }
}
